[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "rhea"
version = "1.0.0"
description = "Reference-free heterogeneity and evolution in assembly graphs"
readme = "README.md"

[project.scripts]
rhea = "rhea:main"

[tool.setuptools]
packages = ["rhea"]

[project.urls]
Repository = "https://github.com/treangenlab/rhea"
